language: java
sudo: false
install: ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -Dfindbugs.skip=true -B -V
jdk:
    - oraclejdk9
    - oraclejdk8
    - openjdk8

cache:
    directories:
        - $HOME/.m2
